GET https://agile-stream-92176.herokuapp.com/eventos
Content-Type: application/json

###

GET https://agile-stream-92176.herokuapp.com/twitter/1
Content-Type: application/json


###

GET https://agile-stream-92176.herokuapp.com/eventos/1
Content-Type: application/json

###

GET https://agile-stream-92176.herokuapp.com/eventosdestacados
Content-Type: application/json

###

GET https://agile-stream-92176.herokuapp.com/usuario/eventos/1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c3VhcmlvIjoiZ3ZlbGFzY28iLCJpZCI6MiwiaWF0IjoxNjI4MjE0ODMyfQ.SuVOYTFw5yA6IYuVBFHZwFOURtDVaar49HlXYavTwt0
