//Crear evento con detalles

POST https://agile-stream-92176.herokuapp.com/eventodetalles
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c3VhcmlvIjoiZ3ZlbGFzY28iLCJpZCI6MiwiaWF0IjoxNjI4MjE0ODMyfQ.SuVOYTFw5yA6IYuVBFHZwFOURtDVaar49HlXYavTwt0

 { 
    "titulo":"Evento",
    "descripcion":"este es mi primer evento",
    "destacado":false,
    "imagenUrl":"www.primerevento.com", 
    "localidad":"san juan",
    "detalles":[
        {
            "fecha":"15/08/2021",
            "hora":"17:00",
            "precio":700
        },
        {
            "fecha":"21/08/2021",
            "hora":"21:00",
            "precio":2000
        }
    ]
}
