POST https://agile-stream-92176.herokuapp.com/usuario
Content-Type: application/json


{
    "nombre":"Guillermo",
    "apellido":"Velasco",
    "usuario":"gvelasco",
    "clave":"123"
}

###

POST https://agile-stream-92176.herokuapp.com/usuario
Content-Type: application/json


{
    "usuario":"usuario2",
    "clave":"123"
}
